version: 2
image: ubuntu:16.04
jobs:
  install-dependencies:
    docker:
      - image: node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Install Dependencies
          command: yarn install --dev
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
  test:
    docker:
      - image: node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Run unit tests
          command: yarn test --coverage
      - run:
          name: Run e2e tests
          command: yarn test:e2e
  lint:
    docker:
      - image: node:10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "yarn.lock" }}
          - dependencies-
      - run:
          name: Check lint application
          command: yarn lint
      - run:
          name: Check lint specs
          command: yarn lint:spec
  build:
    docker:
      - image: circleci/python
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install aws cli
          command: |
            sudo pip install awscli
            aws --version
      # - run:
      #     name: Login aws ecr
      #     command: $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - run:
          name: Build docker tag
          command: |
            docker build -t $OWNER/$CONTAINER_NAME:latest .
            docker tag $OWNER/$CONTAINER_NAME:latest $OWNER/$CONTAINER_NAME:${CIRCLE_TAG:-CIRCLE_BRANCH}
            mkdir -p docker-images
            docker save -o docker-images/cpcon-csv-app.tar $OWNER/$CONTAINER_NAME:latest
      - persist_to_workspace:
          root: docker-images
          paths:
            - cpcon-csv-app.tar

workflows:
  version: 2
  lint-test-and-build:
    jobs:
    - install-dependencies:
        filters:
          tags:
            only: /^([0-9]+).([0-9]+).([0-9]+)$/
          branches:
            only: /^(develop|master)$/
    - test:
        requires:
          - install-dependencies
        filters:
          tags:
            only: /^([0-9]+).([0-9]+).([0-9]+)$/
          branches:
            only: /^(develop|master)$/
    - lint:
        requires:
          - install-dependencies
        filters:
          tags:
            only: /^([0-9]+).([0-9]+).([0-9]+)$/
          branches:
            only: /^(develop|master)$/
    - build:
        requires:
          - lint
          - test
        filters:
          tags:
            only: /^([0-9]+).([0-9]+).([0-9]+)$/
          branches:
            only: /^(develop|master)$/
    # - deploy:
    #     requires:
    #       - build
    #     filters:
    #       tags:
    #         only: /^([0-9]+).([0-9]+).([0-9]+)$/
    #       branches:
    #         ignore: /.*/
